sudo: required
services:
  - docker

befor_install:
  - docker build -t pinwi93/docker-react -f Dockerfile.dev .

script:
  - docker run pinwi93/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-718049919144"
  bucket_path: "docker-react"
  on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acess_key:
      secure: "$AWS_SECRET_KEY"
